import React from 'react';
import { CodeBlock } from '../components/CodeBlock';

export function Streaming() {
  const apiHost = 'http://localhost:3000';

  return (
    <div className="space-y-6">
      <h1 className="text-4xl font-display font-bold tracking-tight">Streaming</h1>
      <p className="text-lg text-[var(--text-secondary)] leading-relaxed">
        The API supports streaming responses using Server-Sent Events (SSE). This allows you to receive partial completions as they are generated by the model.
      </p>

      <div className="pt-6">
        <h2 className="text-2xl font-semibold mb-4">Requesting a Stream</h2>
        <p className="text-[var(--text-secondary)] mb-4">To enable streaming, set the <code>stream</code> parameter to <code>true</code> in your request body.</p>
        <CodeBlock language="bash" code={`curl ${apiHost}/v1/chat/completions \\
  -H "Authorization: Bearer $EBURON_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "model": "eburon-core",
    "messages": [
      {
        "role": "user",
        "content": "Explain quantum computing simply."
      }
    ],
    "stream": true
  }'`} />
      </div>

      <div className="pt-6">
        <h2 className="text-2xl font-semibold mb-4">Stream Output</h2>
        <p className="text-[var(--text-secondary)] mb-4">The API will return a stream of server-sent events. Note how the model name stays branded as <code>eburon-core</code>.</p>
        <CodeBlock language="text" code={`data: {"id":"chatcmpl-eburon-001","object":"chat.completion.chunk","model":"eburon-core","choices":[{"index":0,"delta":{"content":"Quantum"},"finish_reason":null}]}

data: {"id":"chatcmpl-eburon-001","object":"chat.completion.chunk","model":"eburon-core","choices":[{"index":0,"delta":{"content":" computing"},"finish_reason":null}]}

data: [DONE]`} />
      </div>
      
      <p className="text-[var(--text-secondary)] mt-4">
        Clients should parse each chunk to extract the partial content from <code>choices[0].delta.content</code> and concatenate it to build the final response. The stream ends with <code>data: [DONE]</code>.
      </p>
    </div>
  );
}
